#! /bin/sh

# Additional options that are passed to dlna Sync

case "$1" in
    start)
    printf "Starting dlna-sync: "
    /etc/dlna/dlna_start.sh &
    ;;
    stop)
    ;;
    restart)
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
